# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 974ff826a8ddc36bc7110f5dcbe2f8531a0dc48ddd4a5b343537ad04e5024542efdd0e560913dd9839561ee2f275f870df858ee3b58b3e0989a7c7b1e5af9594

test:
  secret_key_base: 16e0acd780f8e7fe3afc0769d225a192de2626821e3ea6e8cda48f396762132776ae7a2553b5b0c20fdae15a388e6b5a39d3754585716880ea381876653bef6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
